I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/code/places/capsule_early.rpy", line 2, in script
    if first_time_capsule == True:
  File "game/code/places/capsule_early.rpy", line 2, in <module>
    if first_time_capsule == True:
NameError: name 'first_time_capsule' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/code/places/capsule_early.rpy", line 2, in script
    if first_time_capsule == True:
  File "C:\Renpy\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "C:\Renpy\renpy\python.py", line 1083, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Renpy\renpy\python.py", line 1076, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/code/places/capsule_early.rpy", line 2, in <module>
    if first_time_capsule == True:
NameError: name 'first_time_capsule' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.2.22081402
Espaço 233 1.0
Tue Nov 15 22:11:07 2022
